### ISSUE TITLE
Chinese POS problem

### ISSUE THREAD

**Issue by Zhouxx22** [lileipisces/Sentires-Guide#7]
Hello and thank you for your work. When I perform the lexicon task on Chinese, I find that POS tagging is not possible. How to perform POS tasks for Chinese?

**Comment by lileipisces** [comment]
I only tested English text. Please check the original toolkit in README to see how to work on Chinese!

**Comment by Zhouxx22** [comment]
> 我只测试了英文文本。请查看README中的原始工具包以了解如何在中文上工作！

Thank you for your response!
